# Generated by Django 4.1.7 on 2023-04-21 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comun", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Establishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "modified_data",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                (
                    "deleted_date",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Eliminacion"
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=200, null=True)),
                ("code", models.CharField(max_length=200)),
                (
                    "aditional_information",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "web_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "trade_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("customer_id", models.IntegerField(blank=True, default=0, null=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "template_pdf",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("has_igv", models.BooleanField(default=False)),
                (
                    "template_ticket_pdf",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comun.department",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="comun.district"
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="comun.province"
                    ),
                ),
            ],
            options={
                "verbose_name": "establecimiento",
                "verbose_name_plural": "establecimientos",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "modified_data",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                (
                    "deleted_date",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Eliminacion"
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facturacion.establishment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deposito",
                "verbose_name_plural": "Depositos",
            },
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "modified_data",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                (
                    "deleted_date",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Eliminacion"
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("contingency", models.BooleanField(default=False)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comun.documenttype",
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facturacion.establishment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serie",
                "verbose_name_plural": "Series",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "modified_data",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                (
                    "deleted_date",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Eliminacion"
                    ),
                ),
                ("has_igv", models.BooleanField(default=True)),
                ("calculate_quantity", models.BooleanField(default=True)),
                ("has_plastic_tax", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "stock",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "stock_min",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("date_of_due", models.DateField(blank=True, null=True)),
                ("itemcode", models.CharField(blank=True, max_length=200, null=True)),
                ("sunatcode", models.CharField(blank=True, max_length=100, null=True)),
                ("barcode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "amount_plastic_bag_taxes",
                    models.DecimalField(decimal_places=2, default=0.1, max_digits=9),
                ),
                ("image", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image_medium",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "image_small",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "affectation_igv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comun.affectationigv",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="comun.currency"
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="comun.itemtype"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="comun.unit"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facturacion.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "modified_data",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                (
                    "deleted_date",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Eliminacion"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customers", "customers"),
                            ("suppliers", "suppliers"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(max_length=200)),
                ("trade_name", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("condition", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "credit_days",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "address_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comun.address",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comun.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comun.department",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comun.district",
                    ),
                ),
                (
                    "identity_document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comun.identitydocument",
                    ),
                ),
                (
                    "person_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comun.persontype",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comun.province",
                    ),
                ),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["-id"],
            },
        ),
    ]
